### ISSUE TITLE
Respond to message edits

### ISSUE THREAD

**Issue by maxdeviant** [merveilles/Nouvion#78]
See [message_changed](https://api.slack.com/events/message/message_changed) event.

**Comment by passcod** [comment]
What would be super neat is if it edited its response with the new result.

**Comment by maxdeviant** [comment]
That's a little more complicated than I had previously envisioned. I was just thinking for if someone misspelled a command so they can go back and edit it and have Nouvion respond.

But I can look into your suggestion as well and see how hard it would be to implement.

**Comment by passcod** [comment]
If it's too hard we can limit this issue's scope to just your original vision and open a new issue for the advanced behaviour so someone can hack it up if they find inspiration.

**Comment by maxdeviant** [comment]
Yea, feel free to open another issue for that behavior, cause I'm about to close this one out.
